version: '3.8'
services:
  previsoes:
    build: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/output:/app/output
    restart: unless-stopped
